Added background SVGs and illustrations to About us page
smaranjitghose/DocLense pull request #115
Opened 2021-02-17 06:48 UTC by Saransh-cpp

Closes #82

The page right now is minimalistic, please let me know if you want any kind of changes. Thank you!

(MWoC and CWoC participant)

## Screenshots
<p float='left'>
<img src='https://user-images.githubusercontent.com/74055102/108166050-9d2c9d80-7119-11eb-9086-6aa80378cfb5.png' height='500px'/>
<img src='https://user-images.githubusercontent.com/74055102/108166060-a0278e00-7119-11eb-899f-cbc39d3a4ee3.png' height='500px'/>
</p>

2021-02-17 19:19 UTC, anushbhatia requested changes
In light, mode yellow doesn't look good use dark blue or any other colour

2021-02-18 04:29 UTC, Saransh-cpp commented
Will any one of the following color work or should I try other dark colors? Please let me know, thank you.

<p float='left'>
<img src='https://user-images.githubusercontent.com/74055102/108305009-2c47bd00-71cf-11eb-871e-145f816648f0.png' height='500px'/>
<img src='https://user-images.githubusercontent.com/74055102/108305034-37025200-71cf-11eb-8007-50bd8d415bb1.png' height='500px'/>
</p>

2021-02-18 11:01 UTC, anushbhatia commented
#ffce44 use this

2021-02-20 21:23 UTC, smaranjitghose approved these changes

2021-02-21 08:42 UTC, merged