Added Logo and Splashscreen.
smaranjitghose/DocLense pull request #16
Opened 2020-12-30 08:11 UTC by Vrushti24

2020-12-31 17:09 UTC, anushbhatia requested changes
Great work with the home screen @Vrushti24🙌🙌🙌 but don't modify the side nav as it is not working now please resolve that rest everything is working fine.

2020-12-31 17:12 UTC, Vrushti24 commented
Can u explain me in detail what is not working on side nav because I
changed only logo nothing else and I checked that It was working fine so
please let me know in detail about the issue
And thank u .


On Thu, Dec 31, 2020, 10:39 PM Anush Bhatia <notifications@github.com>
wrote:

> *@anushbhatia* requested changes on this pull request.
>
> Great work with the home screen @Vrushti24 <https://github.com/Vrushti24>
> 🙌🙌🙌 but don't modify the side nav as it is not working now please
> resolve that rest everything is working fine.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/smaranjitghose/DocLense/pull/16#pullrequestreview-560520006>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARFAUSFIKSMEHKH6SKJPY3DSXSV4NANCNFSM4VOCBRJQ>
> .
>

2020-12-31 17:13 UTC, anushbhatia commented on lib/main.dart
> +      debugShowCheckedModeBanner: false,
Don't modify the icon I will provide the nav icon soon as it does currently not function.

2020-12-31 17:14 UTC, Vrushti24 commented
Okay great I will do that

On Thu, Dec 31, 2020, 10:43 PM Anush Bhatia <notifications@github.com>
wrote:

> *@anushbhatia* commented on this pull request.
> ------------------------------
>
> In lib/main.dart
> <https://github.com/smaranjitghose/DocLense/pull/16#discussion_r550569527>
> :
>
> >    @override
>    Widget build(BuildContext context) {
>      return MaterialApp(
> -      home: SplashScreen(),
> +      debugShowCheckedModeBanner: false,
>
> Don't modify the icon I will provide the nav icon soon as it does
> currently not function.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/smaranjitghose/DocLense/pull/16#pullrequestreview-560520678>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARFAUSEBSN5EOP4KRU4NDRDSXSWNFANCNFSM4VOCBRJQ>
> .
>

2020-12-31 17:18 UTC, Vrushti24 commented
I will remove the icon from maindrawer.dart ?


On Thu, Dec 31, 2020, 10:44 PM Vrushti Shah <vrushtishah24@gmail.com> wrote:

> Okay great I will do that
>
> On Thu, Dec 31, 2020, 10:43 PM Anush Bhatia <notifications@github.com>
> wrote:
>
>> *@anushbhatia* commented on this pull request.
>> ------------------------------
>>
>> In lib/main.dart
>> <https://github.com/smaranjitghose/DocLense/pull/16#discussion_r550569527>
>> :
>>
>> >    @override
>>    Widget build(BuildContext context) {
>>      return MaterialApp(
>> -      home: SplashScreen(),
>> +      debugShowCheckedModeBanner: false,
>>
>> Don't modify the icon I will provide the nav icon soon as it does
>> currently not function.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/smaranjitghose/DocLense/pull/16#pullrequestreview-560520678>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARFAUSEBSN5EOP4KRU4NDRDSXSWNFANCNFSM4VOCBRJQ>
>> .
>>
>

2020-12-31 17:21 UTC, anushbhatia commented
https://user-images.githubusercontent.com/40017559/103419850-c1104000-4bba-11eb-898b-787cf1921b90.mp4

2020-12-31 17:24 UTC, Vrushti24 commented
I got it i will change that thanks

On Thu, Dec 31, 2020, 10:52 PM Anush Bhatia <notifications@github.com>
wrote:

>
> https://user-images.githubusercontent.com/40017559/103419850-c1104000-4bba-11eb-898b-787cf1921b90.mp4
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/smaranjitghose/DocLense/pull/16#issuecomment-753009895>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARFAUSBEK7DKFJMI5GVCMWLSXSXLTANCNFSM4VOCBRJQ>
> .
>

2020-12-31 18:13 UTC, Vrushti24 commented
I have made the changes and even side nav is also working now how can I add
this to GitHub again Same process like before ?

On Thu, Dec 31, 2020, 10:54 PM Vrushti Shah <vrushtishah24@gmail.com> wrote:

> I got it i will change that thanks
>
> On Thu, Dec 31, 2020, 10:52 PM Anush Bhatia <notifications@github.com>
> wrote:
>
>>
>> https://user-images.githubusercontent.com/40017559/103419850-c1104000-4bba-11eb-898b-787cf1921b90.mp4
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/smaranjitghose/DocLense/pull/16#issuecomment-753009895>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ARFAUSBEK7DKFJMI5GVCMWLSXSXLTANCNFSM4VOCBRJQ>
>> .
>>
>

2020-12-31 18:40 UTC, Vrushti24 commented
I have updated PR #16 please check it if this is properly updated thank u

On Thu, Dec 31, 2020, 11:43 PM Vrushti Shah <vrushtishah24@gmail.com> wrote:

> I have made the changes and even side nav is also working now how can I
> add this to GitHub again Same process like before ?
>
> On Thu, Dec 31, 2020, 10:54 PM Vrushti Shah <vrushtishah24@gmail.com>
> wrote:
>
>> I got it i will change that thanks
>>
>> On Thu, Dec 31, 2020, 10:52 PM Anush Bhatia <notifications@github.com>
>> wrote:
>>
>>>
>>> https://user-images.githubusercontent.com/40017559/103419850-c1104000-4bba-11eb-898b-787cf1921b90.mp4
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/smaranjitghose/DocLense/pull/16#issuecomment-753009895>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/ARFAUSBEK7DKFJMI5GVCMWLSXSXLTANCNFSM4VOCBRJQ>
>>> .
>>>
>>

2021-01-02 16:15 UTC, Vrushti24 commented
@anushbhatia I hope that the issue is solved U can check now PR  #16

2021-01-02 18:27 UTC, merged

2021-01-03 06:03 UTC, Vrushti24 commented
Thank you!

On Sat, Jan 2, 2021, 11:57 PM Anush Bhatia <notifications@github.com> wrote:

> Merged #16 <https://github.com/smaranjitghose/DocLense/pull/16> into main.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/smaranjitghose/DocLense/pull/16#event-4161888561>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARFAUSBMPBI6ZSO6DNJUPT3SX5QSJANCNFSM4VOCBRJQ>
> .
>