made home screen responsive for small screen sizes
smaranjitghose/DocLense pull request #205
Opened 2021-03-18 06:51 UTC by sakshi2707

closes #204

2021-03-18 06:54 UTC, sakshi2707 commented
@smaranjitghose please review and merge this PR

2021-03-18 08:13 UTC, anushbhatia commented
Could you attach a screenshot of smaller devices.

2021-03-18 09:10 UTC, sakshi2707 commented
![20210318_143846](https://user-images.githubusercontent.com/55478753/111600851-ce22ef80-87f7-11eb-8ca6-8d3d32ebe2dc.jpg)
@anushbhatia done

2021-03-18 19:26 UTC, anushbhatia commented
resolve the conflict screenshot is fine to me.

2021-03-19 06:57 UTC, sakshi2707 commented
there is no conflict showing in command line. Can you please help what to do?
![Screenshot (1113)](https://user-images.githubusercontent.com/55478753/111742568-6c718c80-88ae-11eb-89eb-14be13215e92.png)

2021-03-19 08:01 UTC, Saransh-cpp commented
> there is no conflict showing in command line. Can you please help what to do?
> ![Screenshot (1113)](https://user-images.githubusercontent.com/55478753/111742568-6c718c80-88ae-11eb-89eb-14be13215e92.png)

Pull the latest code from the original repo ([this](https://github.com/smaranjitghose/DocLense) one), not the forked repo, and then resolve conflicts.

2021-03-19 08:25 UTC, sakshi2707 commented
@Saransh-cpp Thankyou So much! 
@anushbhatia please add gssoc and level labels and merge it. Thankyou.

2021-03-19 08:36 UTC, Saransh-cpp requested changes
After the following changes the lint tests will pass.

2021-03-19 08:36 UTC, Saransh-cpp commented on lib/home.dart
> +import 'package:doclense/Services/SearchService.dart';
Replace
```dart
import 'package:doclense/Services/SearchService.dart';
```
with 
```dart
import 'package:doclense/Services/search_service.dart';
```

2021-03-19 08:36 UTC, Saransh-cpp commented on lib/home.dart
> +import 'package:doclense/StarredDocuments.dart';
Replace
```dart
import 'package:doclense/Services/StarredDocuments.dart';
```
with
```dart
import 'package:doclense/Services/starred_documents.dart';
```

2021-03-19 16:42 UTC, merged

2021-03-19 16:54 UTC, sakshi2707 commented
Thankyou @anushbhatia . please add gssoc label also in the pr