Camera Modified.... Now After Take Image app not crash
smaranjitghose/DocLense pull request #227
Opened 2021-03-24 10:38 UTC by SamarpanCoder2002

Now app will not crash when take image from camera....(Issue related: #210 )

Video Demo: https://drive.google.com/file/d/1RDKyyhrpEoUwKSvF-aPOlmST7cLVzfB6/view?usp=sharing

I am also a GSSOC'21 participant.....

Thank you

2021-03-24 11:23 UTC, SamarpanCoder2002 commented
hello @anushbhatia .... if it looks good..kindly merge it .... demo video also provided...

2021-03-24 11:55 UTC, Saransh-cpp requested changes
@SamarpanCoder2002 can you please go through all the failed lint checks once and fix them?

2021-03-24 14:54 UTC, SamarpanCoder2002 commented
I think that problem lint check problems related to platform specific OS.... Problems arrive in ubuntu, windows, macos.....But that issues not problem the application.... But some of the isuues, I can't modified, as in one issue, it requested to use is not empty instead of length.... But at there, I have to write length to setup the logic..... So I think that will be not a problem to merge it.... because it works fine..
Thanks @anushbhatia

2021-03-24 16:28 UTC, Saransh-cpp commented
> I think that problem lint check problems related to platform specific OS.... Problems arrive in ubuntu, windows, macos.....But that issues not problem the application.... But some of the isuues, I can't modified, as in one issue, it requested to use is not empty instead of length.... But at there, I have to write length to setup the logic..... So I think that will be not a problem to merge it.... because it works fine..
> Thanks @anushbhatia

The checks are failing because of some minor mistakes in the code (not necessarily errors but maybe a thing that can be replaced with something more efficient or a keyword that won't make a big difference right now but should be added), you can start by solving the smaller issues first and then figure out how to deal with the other issues. Some small issues - 
1. File name should be in small letters (something_like_this.dart).
2. Placing the `'dart'` imports before any other imports.
3. Using `const` wherever a constant constructor is defined or called.

2021-03-24 16:32 UTC, Saransh-cpp requested changes
These are some of the small changes that will get you started with passing the checks

2021-03-24 16:32 UTC, Saransh-cpp commented on lib/cameraOperation.dart
> +                child: Icon(Icons.camera_alt),
Add `const` before `Icon()`

2021-03-24 16:32 UTC, Saransh-cpp commented on lib/cameraOperation.dart
> +                child: Icon(Icons.flip_camera_android_rounded),
Add `const` before `Icon()`

2021-03-24 16:32 UTC, Saransh-cpp commented on lib/cameraOperation.dart
> +                child: Icon(
Add `const` before `Icon()`

2021-03-24 16:32 UTC, Saransh-cpp commented on lib/cameraOperation.dart
> +                backgroundColor: Color.fromRGBO(0, 0, 0, 0.0),
Add `const` before `Color`

2021-03-25 09:19 UTC, SamarpanCoder2002 commented
@anushbhatia Now all checks are passes and it looks fine....You can check again the demo video link..... Please merge it ....Thank u

2021-03-25 20:09 UTC, anushbhatia commented
![Screenshot_20210326_013616_com example doclense](https://user-images.githubusercontent.com/40017559/112536882-06b46180-8dd4-11eb-8c51-d109db76ccb5.jpg)
My camera resolution is afted by this

2021-03-26 07:38 UTC, closed without merging