error in gallery + images getting copied to next pdf
smaranjitghose/DocLense pull request #290
Opened 2021-11-15 20:43 UTC by ayyysh04

fixed the bugs, please check the same @anushbhatia

2021-11-20 16:42 UTC, anushbhatia commented
![Screenshot_20211120-221125.jpg](https://user-images.githubusercontent.com/40017559/142734215-2e335f22-e7d5-452f-892d-de2005b49140.jpg)

Can you change the heading to white color that would be great. Rest amazing work 🥳

2021-11-20 21:43 UTC, ayyysh04 commented
> ![Screenshot_20211120-221125.jpg](https://user-images.githubusercontent.com/40017559/142734215-2e335f22-e7d5-452f-892d-de2005b49140.jpg)
> 
> Can you change the heading to white color that would be great. Rest amazing work 🥳

I have not changed the theme constant, In my phone its showing appbar text in white only. You can check here
`class AppTheme {
  static const Color primaryColor = Colors.white;
}`

2021-11-20 21:44 UTC, ayyysh04 commented
I have not changed the theme constant, In my phone its showing appbar text in white only. You can check here
`
class AppTheme 
{ static const Color primaryColor = Colors.white;
 }`

2021-11-22 09:46 UTC, anushbhatia requested changes

2021-11-22 09:46 UTC, anushbhatia commented on lib/constants/theme_constants.dart
> +        color: AppTheme.primaryColor,
Check this once i think this should be white.

2021-11-22 14:18 UTC, ayyysh04 commented
Done, please check the same @anushbhatia

2021-11-25 14:58 UTC, merged

2021-11-25 15:07 UTC, anushbhatia commented
Awesome Work @ayyysh04 looking forward to more contributions from your end.
![Alt Text](https://media.giphy.com/media/pRknW0j4jTDkd2qKHX/giphy.gif)